name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering
    inputs:
      branch:
        description: "Branch to build"
        required: false
        default: "main"
      verbosity:
        description: "Verbosity level for dotnet commands (minimal, normal, detailed, diagnostic)"
        required: false
        default: "detailed"

env:
  VERBOSITY: quiet

jobs:
  pull-src-code:
    runs-on: ubuntu-latest
      # Determine the branch to checkout
      - name: Determine branch to checkout
        id: determine-branch
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "BRANCH=${{ inputs.branch }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "BRANCH=main" >> $GITHUB_ENV
          fi
          echo "The branch that will be checked out is: $BRANCH"

      # Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ref: ${{ env.BRANCH }}
  build:
    steps:
      # Setup .NET Core version
      - name: Setup .NET Core version 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      # Determine verbosity dynamically
      - name: Set Variables
        id: vars
        run: |
          echo "VERBOSITY=${{ inputs.verbosity || env.VERBOSITY }}" >> $GITHUB_ENV

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore --no-cache --verbosity $VERBOSITY

      # Build the solution
      - name: Build
        run: dotnet build --configuration Release --no-restore --verbosity $VERBOSITY

      # Run tests
      - name: Run Tests
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" --verbosity $VERBOSITY
