name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering
    inputs:
      branch:
        description: 'Branch to build'
        required: false
        default: 'main'
      verbosity:
        description: 'Verbosity level for dotnet commands (minimal, normal, detailed, diagnostic)'
        required: false
        default: 'detailed'

env:
  VERBOSITY: quiet

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch || github.ref_name }} # Use input branch or default to the triggered branch

      # Setup .NET Core version
      - name: Setup .NET Core version 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      # Determine verbosity dynamically
      - name: Set Variables
        id: vars
        run: |
          echo "VERBOSITY=${{ inputs.verbosity || env.VERBOSITY }}" >> $GITHUB_ENV

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore --no-cache --verbosity $VERBOSITY

      # Build the solution
      - name: Build
        run: dotnet build --configuration Release --no-restore --verbosity $VERBOSITY
