name: .NET Build and Test

on:
  push:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering
    inputs:
      branch:
        description: 'Branch to build'
        required: false
        default: 'main'
      verbosity:
        description: 'Verbosity level for dotnet commands (minimal, normal, detailed, diagnostic)'
        required: false
        default: 'detailed'

env:
  VERBOSITY: quiet

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch || github.ref_name }} # Use input branch or default to the triggered branch

      # Sets up .NET Core version
      - name: Setup .NET Core version 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      # Determines verbosity dynamically
      - name: Set Variables
        id: vars
        run: |
          echo "VERBOSITY=${{ inputs.verbosity || env.VERBOSITY }}" >> $GITHUB_ENV

      # Restores dependencies
      - name: Restore dependencies
        run: dotnet restore --no-cache --verbosity $VERBOSITY

      # Builds the solution
      - name: Build
        run: dotnet build --configuration Release --no-restore --verbosity $VERBOSITY
      
      # Creates the artifact
      - name: Publish artifact
        run: dotnet publish -c Release -o artifacts --verbosity $VERBOSITY --no-build --no-restore
      
      # Uploads the artifact to github
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: portfolio
          path: artifacts/
          retention-days: 1

      # Run tests
      - name: Run Tests
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" --verbosity $VERBOSITY